IMAGES = {
    'gcr.io/google-containers/coredns': ['1.2.2'],
    'gcr.io/google-containers/kube-apiserver': ['v1.12.3'],
    'gcr.io/google-containers/kube-controller-manager': ['v1.12.3'],
    'gcr.io/google-containers/kube-scheduler': ['v1.12.3'],
    'gcr.io/google-containers/kube-proxy': ['v1.12.3'],
    'gcr.io/google-containers/pause': ['3.1'],
    'gcr.io/google_containers/cluster-proportional-autoscaler-amd64': ['1.1.2', '1.3.0'],
    'gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64': ['1.14.13'],
    'gcr.io/google_containers/k8s-dns-kube-dns-amd64': ['1.14.13'],
    'gcr.io/google_containers/k8s-dns-sidecar-amd64': ['1.14.13'],
    'gcr.io/google_containers/kube-registry-proxy': ['0.4'],
    'gcr.io/google_containers/kubernetes-dashboard-amd64': ['v1.10.0'],
    'gcr.io/google_containers/pause-amd64': ['3.1'],
    'gcr.io/kubernetes-helm/tiller': ['v2.11.0'],
    'k8s.gcr.io/addon-resizer': ['1.8.3'],
    'k8s.gcr.io/metrics-server-amd64': ['v0.3.1'],
    'quay.io/calico/cni': ['v3.1.3'],
    'quay.io/calico/ctl': ['v3.1.3'],
    'quay.io/calico/kube-controllers': ['v3.1.3'],
    'quay.io/calico/node': ['v3.1.3'],
    'quay.io/calico/routereflector': ['v0.6.1'],
    'quay.io/coreos/etcd': ['v3.2.24'],
    'quay.io/external_storage/cephfs-provisioner': ['v2.1.0-k8s1.11'],
    'quay.io/external_storage/local-volume-provisioner': ['v2.1.0'],
    'quay.io/jetstack/cert-manager-controller': ['v0.5.2'],
    'quay.io/kubernetes-ingress-controller/nginx-ingress-controller': ['0.21.0'],
    'quay.io/l23network/k8s-netchecker-agent': ['v1.0'],
    'quay.io/l23network/k8s-netchecker-server': ['v1.0']
}
